### ISSUE TITLE
Not Working On KitKat 4.4

### ISSUE THREAD

**Issue by Baubascat** [Dees-Troy/SimpleCoil#1]
I bought a cheap BLU Android phone off amazon and when I try to install SimpleCoil I get a "Parse error". Does SimpleCoil work on KitKat 4.4?

**Comment by Dees-Troy** [comment]
Sorry, SimpleCoil is for Android 5.0 or higher. It might be possible to rewrite parts of the app to work on 4.4 but I have no plans to support it myself.

**Comment by ApkNewb** [comment]
Dees-Troy, would you be interested in providing assistance in getting a 4.4.2 fork started if others were willing to do the work?  New to apk, but have coding experience.  Thanks
