### ISSUE TITLE
Windows dedicate server

### ISSUE THREAD

**Issue by Nebur692** [Dees-Troy/SimpleCoil#13]
Create app for dedicate server on Windows 10

**Comment by Dees-Troy** [comment]
Sorry, but this is completely out of scope. You can buy a cheap tablet or phone for cheap or you might even be able to run the server on a Chromebook that allows you to run Android apps. The app is open source and the protocol is relatively simple and written in Java which is cross-platform. Feel free to port it to Windows yourself if you really need this feature.
