### ISSUE TITLE
Samsung Galaxy Tab A Bluetooth

### ISSUE THREAD

**Issue by tonystech** [Dees-Troy/SimpleCoil#15]
Hey! Fantastic app! I found this because I'm trying to connect my two weapons to two separate Samsung Galaxy Tab A's. The official app just stays on, "Searching" while trying to connect. I tried SimpleCoil but the connection fails right away. Is it just the device that doesn't work? Isn't bluetooth protocol standard? 

Thank so much for making this!

**Comment by Dees-Troy** [comment]
There are a handful of devices that just don't seem to implement Bluetooth Low Energy protocol correctly. Unfortunately there's not much I can do inside the app to fix it. The fix would almost certainly have to come from Samsung.
