### ISSUE TITLE
Nexus 6 Bluetooth? 

### ISSUE THREAD

**Issue by Cagny** [Dees-Troy/SimpleCoil#4]
Hello! Thank you for all your hard work on this project! I was able to install SimpleCoil on a Nexus 6 but am not able to connect to any Recoil gun. Have you had any success with a Nexus 6? Looking into its specs: The Bluetooth is listed as 4.1, A2DP, LE.

Thanks!

**Comment by Dees-Troy** [comment]
I have had difficulty with other Motorola phones running Android 7 and the Nexus 6 is made by Motorola. I too am not able to connect my Nexus 6 with a Recoil blaster using both SimpleCoil and the official Recoil app. You might try downloading a factory image from Android 6.0 for the Nexus 6 and see if that works any better.

**Comment by FeralBytes** [comment]
Just a question did you come up with a fix, or just decided Android has moved on since?

**Comment by Dees-Troy** [comment]
As I said, other Motorola phones running Android 7.1 also have problems connecting to the Recoil blasters. The Nexus 6 was manufactured by Motorola for Google and its likely that Motorola was responsible for some of the lower level software / firmware. Whatever bug this is seems to affect multiple Motorola devices running Android 7.1. Motorola devices running 6.0 and 8.0 do not have this issue. You are welcome to try to see if you can find a solution for this problem if you like. I also tried pairing with the official Recoil app and saw the same problem. Based on what I've seen, I am chalking this problem up to an issue with Motorola's Bluetooth LE implementation in Android 7.1 and I don't plan on looking into this issue any further. Sorry.
