### ISSUE TITLE
immune to grenade damage

### ISSUE THREAD

**Issue by CydFSA** [Dees-Troy/SimpleCoil#5]
When in team games (both 2 and 4 teams) the highest numbered team is immune to grenade damage. Workaround; use the 4 team game and only use teams 1,2 and 3.

**Comment by Dees-Troy** [comment]
https://github.com/Dees-Troy/SimpleCoil/commit/a7cc66e1966ce9368e443cbc8ac20d132b14185a

This patch will fix the grenade damage in team games.

**Comment by Dees-Troy** [comment]
Fixed in 1.10
